---
version: 2
updates:
  # 1️⃣ Dépendances Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/" # Racine du projet
    schedule:
      interval: "weekly"  # Peut être daily / weekly / monthly
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
